default: &default

development:
    <<: *default
    database: db/development.sqlite3
    adapter: sqlite3
    pool: 5
    timeout: 5000
    
test:
    <<: *default
    database: db/development.sqlite3_test

production:
    <<: *default
    database: db/development.sqlite3_production